In [1]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])

print(i.shape)

(5,)


In [2]:
import numpy as np

i = np.array([[10,20,30,40,50],
              [60,70,80,90,100]])

print(i.shape)

(2, 5)


In [3]:
import numpy as np

i = np.array([
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]],
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]]
])

print(i.shape)

(2, 3, 5)


In [4]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90,100])

j = i.reshape(5,2)

j

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [5]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])

j = i.reshape(4,3)

j

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [6]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130,140,150,160])

j = i.reshape(2,2,4)

j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [7]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140,150, 160])

j = i.reshape(2,4,2)

j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [8]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140,150,160])

j = i.reshape(2,4,-1)

j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [9]:
i = np.array([
[[10, 20, 30], [40, 50, 60]],
[[70, 80, 90], [100, 110, 120]],
[[130, 140,150],[1,2,3]]
])

j = i.reshape(-1)

j

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150,   1,   2,   3])

In [10]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 70])

for j in i:
    print(j)


10
20
30
40
50
70


In [11]:
import numpy as np

i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])

for j in i:
    print(j)

[10 20 30]
[40 50 60]
[70 80 90]
